name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    name: Build & DEploy Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: 🧱 Клониране на кода
        uses: actions/checkout@v3

      - name: 🛠️ Права за Bash скриптове
        run: chmod +x ci_pipeline.sh deploy.sh

      - name: ✅ Изпълнение на CI скрипта
        run: ./ci_pipeline.sh

      - name: 🚀 Deploy (ако CI мине успешно)
        run: ./deploy.sh
